# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd26fb7a5fc430fcea34570ff1547e58"
name = "Dreamward"
application_url = "https://godreamward.com/api/shopify/install"
embedded = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://godreamward.com/api/shopify/webhook"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,read_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://godreamward.com/api/shopify/oauth/callback" ]
