// lib/pdf/genericReport.tsx
//
// Generic, table-based PDF for the business reports. Any report POSTs a
// spec (title + meta lines + tables) to /api/reports/export/pdf, which
// renders this. Keeps @react-pdf/renderer server-side (the client never
// imports it) and gives every report a consistent, polished PDF without
// per-report PDF code.

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

export interface PdfTable {
  heading?: string;
  columns: string[];
  rows: (string | number)[][];
}

export interface ReportPdfSpec {
  title: string;
  meta: string[];
  tables: PdfTable[];
  businessName?: string;
}

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#0f172a",
    padding: 36,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 1.5,
    borderBottomColor: "#1e293b",
    paddingBottom: 8,
    marginBottom: 12,
  },
  brand: { fontSize: 13, fontWeight: "bold" },
  generated: { fontSize: 8, color: "#94a3b8" },
  title: { fontSize: 16, fontWeight: "bold", marginBottom: 2 },
  meta: { fontSize: 9, color: "#475569", marginBottom: 1 },
  section: {
    marginTop: 12,
    padding: 10,
    border: "1pt solid #e2e8f0",
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#0f172a",
  },
  headerRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    paddingBottom: 3,
    marginBottom: 3,
  },
  row: {
    flexDirection: "row",
    paddingVertical: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: "#f1f5f9",
  },
  cell: { flex: 1, fontSize: 9 },
  cellFirst: { flex: 2, fontSize: 9 },
  cellRight: { textAlign: "right" },
  headerCell: { fontSize: 8, color: "#64748b", fontWeight: "bold" },
});

function GenericReportDoc({ spec }: { spec: ReportPdfSpec }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page} wrap>
        <View style={styles.header}>
          <Text style={styles.brand}>{spec.businessName || "Dreamward"}</Text>
          <Text style={styles.generated}>Generated by Dreamward</Text>
        </View>
        <Text style={styles.title}>{spec.title}</Text>
        {spec.meta.map((m, i) => (
          <Text key={i} style={styles.meta}>
            {m}
          </Text>
        ))}
        {spec.tables.map((t, ti) => (
          <View key={ti} style={styles.section} wrap={false}>
            {t.heading ? (
              <Text style={styles.sectionTitle}>{t.heading}</Text>
            ) : null}
            <View style={styles.headerRow}>
              {t.columns.map((c, ci) => (
                <Text
                  key={ci}
                  style={[
                    ci === 0 ? styles.cellFirst : styles.cell,
                    styles.headerCell,
                    ci === 0 ? {} : styles.cellRight,
                  ]}
                >
                  {c}
                </Text>
              ))}
            </View>
            {t.rows.map((r, ri) => (
              <View key={ri} style={styles.row}>
                {r.map((cell, ci) => (
                  <Text
                    key={ci}
                    style={[
                      ci === 0 ? styles.cellFirst : styles.cell,
                      ci === 0 ? {} : styles.cellRight,
                    ]}
                  >
                    {String(cell)}
                  </Text>
                ))}
              </View>
            ))}
          </View>
        ))}
      </Page>
    </Document>
  );
}

export async function renderGenericReportPdf(
  spec: ReportPdfSpec
): Promise<Buffer> {
  return renderToBuffer(<GenericReportDoc spec={spec} />);
}
